### ISSUE TITLE
Request parm with no value being stripped

### ISSUE THREAD

**Issue by kcbaltz** [Netflix/zuul#141] opened 2015-08-05 16:27 UTC
I have a CXF web service that I'm trying to put behind a Zuul proxy.  The URL to request the WSDL looks like (/api/foo?wsdl).  When I request it through Zuul, it fails and it appears to be because Zuul isn't passing the ?wsdl because it doesn't have a value (e.g. ?wsdl=bar).   This is with Zuul 1.0.28, the one we get from spring-cloud-starter-zuul:1.0.2.RELEASE.

**Comment by spencergibb** [comment] 2015-08-05 16:55
I would raise an issue [here](https://github.com/spring-cloud/spring-cloud-netflix/issues) before bringing this straight to Netflix.  There are custom filters there that might actually be the problem, not zuul itself.

**Comment by kcbaltz** [comment] 2015-08-05 17:06
OK, thanks, I'll try that.  I was trying to spot the point in the code that makes the proxy request.  Is that standard Zuul or is it something added by a Filter?

**Comment by kcbaltz** [comment] 2015-08-05 20:24
I found the problem.  It's in HTTPRequestUtils.getQueryParams().  I'll submit a patch soon.

**Comment by kcbaltz** [comment] 2015-08-06 21:56
Pull Request submitted:  https://github.com/Netflix/zuul/pull/142

**Comment by nedenom** [comment] 2015-12-09 16:12
I built a 1.1.0-SNAPSHOT on Oct 3 to get this patch and it worked fine. However, after bumping to official 1.1.0 release, it no longer works again. Could this be caused by a regression later in the 1.1.0?

I'm also using Spring Cloud Netflix. Neither spring-cloud-starter-zuul:1.0.4.RELEASE or 1.1.0.M1 works with zuul-core-1.1.0. But if go back to my zuul-core-1.1.0-SNAPSHOT again it does in fact work for both spring cloud versions.

**Comment by polarbizzle** [comment] 2015-12-09 17:21
The fix you submitted in PR #142 appears intact in the 1.1.0 release. I've just been looking over the changes between yours and the release and I don't see anything glaring that would conflict with the updated HTTPRequestUtils. I've just run a simple test locally hitting a url of the same form (?wsdl) with 1.1.0 and it doesn't strip out the param. I'm not familiar with how zuul gets set up in spring cloud but perhaps there is something going on in one of the spring cloud filters that strips such params? A cursory clicking through the spring cloud starter code on github hasn't yielded me any insight into what might be going on.

**Comment by nedenom** [comment] 2015-12-10 13:46
Yes, you are right. I seems there was something else in 1.1.0 between Oct 3 snapshot and final that broke spring-cloud-zuul. It looks like it is fixed in latest spring-cloud snapshot though

**Closed** 2018-01-05 00:05 UTC
